# ACTIVEVIEW v8.0 Humanoid 实体配置 (configs/humanoid.yaml)

avatar_name: "neutral_0"
ground_offset: 0.0
scale: 1.0
default_yaw: 0.0
assets_root: "robot/habitat-lab/data/versioned_data/habitat_humanoids"
urdf_filename: "neutral_0.urdf"
floor_height: -1.60
base_pelvis_offset: 0.90
semantic_id: 100
semantic_enabled: true
